disabled_rules:
- trailing_whitespace
- xctfail_message

included:
excluded:
- Pods
- OpenMarket/AppDelegate.swift
- OpenMarket/SceneDelegate.swift

line_length: 99
identifier_name:
    max_length: 45
